name: Rom-Extractor
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
    
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2
   
       - name: EnvSetup
         run: |
              sudo apt install python3 brotli aria2 curl -y
              mkdir Rom
              mkdir Rom/Unzip

       - name: Download Rom
         working-directory: Rom
         run: |
              aria2c ${{ github.event.inputs.ROM_URL }}

       - name: Unzip Rom
         working-directory: Rom
         run: |
              git clone https://github.com/xc112lg/huawei-creator
              cp * ./huawei-creator/
              cd huawei-creator
              sudo ./run-huawei-aonly.sh systemAB.img "LeaOS" "PRA-LX1" "N"
       
       - name: Upload
         working-directory: Rom
         run: |
              cd huawei-creator
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet s-aonly.img

